input.onButtonPressed(Button.A, function () {
    basic.showIcon(IconNames.Heart)
    basic.pause(3000)
    basic.showIcon(IconNames.SmallHeart)
    basic.pause(3000)
    basic.showIcon(IconNames.No)
    basic.pause(3000)
    basic.clearScreen()
})
input.onButtonPressed(Button.AB, function () {
    basic.showString("hi")
    basic.showString("bye")
    basic.pause(2000)
    basic.showIcon(IconNames.Happy)
    basic.showIcon(IconNames.Asleep)
    basic.pause(2000)
    basic.clearScreen()
})
input.onButtonPressed(Button.B, function () {
    basic.showNumber(10)
    basic.pause(2000)
    basic.showString("aum")
    basic.pause(2000)
    basic.clearScreen()
})
basic.showString("wongsathon")
basic.pause(3000)
basic.showString("ubolrat")
basic.pause(3000)
basic.showString("4/2")
basic.pause(3000)
